name: NounsAuctionHouse
description: Randomly generated avatar NFTs auctioned daily.
networks:
- id: 1
  start_block: 0
  contracts:
  - name: NounsAuctionHouse
    abi_file_path: abis/NounsAuctionHouse.json
    handler: src/EventHandlers.ts
    address:
    - 0x830BD73E4184ceF73443C15111a1DF14e495C706
    events:
    - event: AuctionCreated
      requiredEntities: []
    - event: AuctionBid
      requiredEntities: []
    - event: AuctionExtended
      requiredEntities: []
    - event: AuctionSettled
      requiredEntities: []
  - name: NounsDAO
    abi_file_path: abis/NounsDAO.json
    handler: src/EventHandlers.ts
    address:
    - 0x6f3E6272A167e8AcCb32072d08E0957F9c79223d
    events:
    - event: ProposalCreatedWithRequirements
      requiredEntities: []
    - event: ProposalCreatedWithRequirements
      requiredEntities: []
    - event: ProposalCreatedOnTimelockV1
      requiredEntities: []
    - event: ProposalCanceled
      requiredEntities: []
    - event: ProposalVetoed
      requiredEntities: []
    - event: ProposalQueued
      requiredEntities: []
    - event: ProposalExecuted
      requiredEntities: []
    - event: VoteCast
      requiredEntities: []
    - event: MinQuorumVotesBPSSet
      requiredEntities: []
    - event: MaxQuorumVotesBPSSet
      requiredEntities: []
    - event: QuorumCoefficientSet
      requiredEntities: []
    - event: ProposalUpdated
      requiredEntities: []
    - event: ProposalDescriptionUpdated
      requiredEntities: []
    - event: ProposalTransactionsUpdated
      requiredEntities: []
    - event: ProposalObjectionPeriodSet
      requiredEntities: []
    - event: SignatureCancelled
      requiredEntities: []
    - event: EscrowedToFork
      requiredEntities: []
    - event: WithdrawFromForkEscrow
      requiredEntities: []
    - event: ExecuteFork
      requiredEntities: []
    - event: JoinFork
      requiredEntities: []
    - event: VoteSnapshotBlockSwitchProposalIdSet
      requiredEntities: []
  - name: NounsDAOData
    abi_file_path: abis/NounsDAOData.json
    handler: src/EventHandlers.ts
    address:
    - 0xf790A5f59678dd733fb3De93493A91f472ca1365
    events:
    - event: ProposalCandidateCreated
      requiredEntities: []
    - event: ProposalCandidateUpdated
      requiredEntities: []
    - event: ProposalCandidateCanceled
      requiredEntities: []
    - event: SignatureAdded
      requiredEntities: []
    - event: FeedbackSent
      requiredEntities: []
    - event: CandidateFeedbackSent
      requiredEntities: []
  - name: NounsToken
    abi_file_path: abis/NounsToken.json
    handler: src/EventHandlers.ts
    address:
    - 0x9C8fF314C9Bc7F6e59A9d9225Fb22946427eDC03
    events:
    - event: NounCreated
      requiredEntities: []
    - event: DelegateChanged
      requiredEntities: []
    - event: DelegateVotesChanged
      requiredEntities: []
    - event: Transfer
      requiredEntities: []
