name: NounsAuctionContract
description: ''
networks:
- id: 5
  start_block: 0
  contracts:
  - name: ERC721
    abi_file_path: abis/ERC721.json
    handler: src/EventHandlers.ts
    address:
    - 0x7851148A467E2E0B942e71E77182258ade0ecA5F
    events:
    - event: CapacityIncreased
      requiredEntities: []
    - event: Transfer
      requiredEntities: []
  - name: NounsAuctionContract
    abi_file_path: abis/NounsAuctionContract.json
    handler: src/EventHandlers.ts
    address:
    - 0x7FeAaF56Bc68e3364a3cC5D34C943B81b848e86b
    events:
    - event: CreatedBid
      requiredEntities: []
    - event: SettledAndCreatedAuction
      requiredEntities: []
    - event: WithdrawMoney
      requiredEntities: []
